### ISSUE TITLE
This is awesome 😁  Could I ask a few questions?

### ISSUE THREAD

**Issue by StoneCypher** [titu1994/Neural-Style-Transfer-Windows#2]
this tool is really cool :grinning: 

a couple quick questions if that's okay?

1. does it make a quality difference or speed difference to be on vgg16 vs vgg19?
1. is there a reason to keep my textures the same size or aspect ratio as my bases?
1. are grams just pixels?  is a 600 gram matrix a 600x600 image?  
    1. if so, how big of a gram matrix is a 400x500 image?
1. how do i calculate the maximum image size that will fit in my card's memory?
1. will this split across multiple cards, to do larger images?  (i already know about waifu)

**Comment by titu1994** [comment]
Slight quality differences between 16 and 19. 

Keeping the texture the same aspect ratio helps the correct part of the style to overlap the part of the image. It's not needed much, and only changes the results for a few styles. 

Gram Matrices are not pixels. They are square matrices that contain correlation statistics of features of that specific layer, and therefore the size is dependent on the number of channels of that layer. 

You try larger and larger image until you oom. No real way to know. If you want larger image but poor quality, use the basic Network.py. If you want better quality but smaller size, use INetwork.py

No, this does not do distributed inference.

**Comment by StoneCypher** [comment]
Not counting postprocessing techniques like waifu, what can I do to achieve larger images?

**Comment by titu1994** [comment]
Photoshop upscaling, and then using Nik add-ons to remove upscaling artifacts v
